### ISSUE TITLE
Unable to configure Reveal-stage for Thursday Demo

### ISSUE THREAD

**Issue by craigappl** [onaio/reveal-frontend#608]
I am not able to successfully configure reveal stage's team assignment to be able to download it for the reference-app v2.6.2.

## Target Outcome
1) Annie can login on Thursday morning to the users listed below in the reference app v2.6.2.
2) Five plans are available (1 IRS, 1 MDA and 3 Case Triggered as defined below)
3) (stretch) Annie can create plans in the Web UI and have things auto populate in the client

## Things that need to be done
1) Please address the problems below regarding app crash. Please release an APK if you need to for the reference app and communicate that with Annie at Akros.
2) Please assign the 3 plans Greg created to the teams referenced in parenthesis.
3) Please test that you can login with all of the users, plans load and tasks are generated.

## Problems:
1) The app crashes every time I tap the operational area in the Android client.
`
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object com.unnamed.b.atv.model.TreeNode.getValue()' on a null object reference
       at com.vijay.jsonwizard.customviews.TreeViewDialog.extractName(TreeViewDialog.java:152)
       at com.vijay.jsonwizard.customviews.TreeViewDialog.setValue(TreeViewDialog.java:179)
       at com.vijay.jsonwizard.customviews.TreeViewDialog.init(TreeViewDialog.java:113)
       at com.vijay.jsonwizard.customviews.TreeViewDialog.<init>(TreeViewDialog.java:44)
       at org.smartregister.reveal.view.DrawerMenuView.showOperationalAreaSelector(DrawerMenuView.java:205)
       at org.smartregister.reveal.presenter.BaseDrawerPresenter.onShowOperationalAreaSelector(BaseDrawerPresenter.java:153)
       at org.smartregister.reveal.view.DrawerMenuView.onClick(DrawerMenuView.java:275)
       at android.view.View.performClick(View.java:6294)
       at android.view.View$PerformClick.run(View.java:24774)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6518)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`
2) The users TCP01 and TCP02 show the wrong hierarchy in the app. They should the Zambia hierarchy, not the hierarchy that starts with 'ra'

3) I have not been able to test if Nifi is in a state where plans generate tasks when they are created.

## Pierre loaded in a new hierarchy to reveal-stage on Monday prefaced with ra for Reference app.
![image](https://user-images.githubusercontent.com/6067053/69291335-c0d00380-0bb7-11ea-9b5c-74304c068e0e.png)

## I Created Users in OpenMRS (Password Datacollector1)
- CD01 
- TCP01
- TCP02
- NL01
- SD01

## I Created Practitioners in Reveal
`
[
  {
    "identifier": "2b2e31bf-433b-5b45-8028-4ddf7c2ecba1",
    "active": true,
    "name": "Chadiza Data Collector 1",
    "userId": "4b6fd290-399b-485c-810a-744bc6a3c575",
    "username": "CD01"
  },
  {
    "identifier": "074ed18b-0e11-5f89-93e5-f2342a300acc",
    "active": true,
    "name": "Chipata Data Collector 1",
    "userId": "fd1d9b9e-fbf2-4ab1-b3a9-b6586f098825",
    "username": "TCP01"
  },
  {
    "identifier": "fc21f514-d145-513a-afb9-6f3108f14d5f",
    "active": true,
    "name": "Chipata Data Collector 2",
    "userId": "b6317f75-7ad6-4fef-8c44-3699e21e3d09",
    "username": "TCP02"
  },
  {
    "identifier": "f8a81d2e-d514-5489-bc46-84ee3c969b77",
    "active": true,
    "name": "Nchelenge Data Collector 1",
    "userId": "915f4bba-dd00-45cd-9336-51e690ec6fbb",
    "username": "NL01"
  },
  {
    "identifier": "6722ba46-48e9-5e59-9fc1-71aed0cc3b69",
    "active": true,
    "name": "Sinda Data Collector 1",
    "userId": "2437aace-c9b9-4806-841e-bf5d1b65ab7e",
    "username": "SD01"
  }
]
`

## I Created Organizations in Reveal
`
[
{"id":45,"identifier":"96f841eb-6478-50ef-abba-67021473d4bb","active":true,"name":"Chadiza1","type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/organization-type","code":"team","display":"Team"}]}},{"id":46,"identifier":"51fb5086-5a2d-54d1-9833-908daba23f82","active":true,"name":"Chipata1","type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/organization-type","code":"team","display":"Team"}]}},{"id":48,"identifier":"97809856-5c31-5a4e-abb2-efe152a0b715","active":true,"name":"Nchelenge1","type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/organization-type","code":"team","display":"Team"}]}},{"id":47,"identifier":"79a66ddb-d563-5e99-8177-fda2ab13e384","active":true,"name":"Sinda1","type":{"coding":[{"system":"http://terminology.hl7.org/CodeSystem/organization-type","code":"team","display":"Team"}]}}]
`

## I Created PractitionerRoles
`
[
  {
    "identifier": "2a553b33-f997-554e-b726-d30641b0d155",
    "active": true,
    "organization": "97809856-5c31-5a4e-abb2-efe152a0b715",
    "practitioner": "6722ba46-48e9-5e59-9fc1-71aed0cc3b69",
    "code": {
      "text": "Community Health Worker"
    }
  },
  {
    "identifier": "3ba80c51-e025-5b26-b37d-ef000e2a9607",
    "active": true,
    "organization": "79a66ddb-d563-5e99-8177-fda2ab13e384",
    "practitioner": "f8a81d2e-d514-5489-bc46-84ee3c969b77",
    "code": {
      "text": "Community Health Worker"
    }
  },
  {
    "identifier": "8c502a18-1bf7-5431-81ad-3b6c897b3359",
    "active": true,
    "organization": "51fb5086-5a2d-54d1-9833-908daba23f82",
    "practitioner": "074ed18b-0e11-5f89-93e5-f2342a300acc",
    "code": {
      "text": "Community Health Worker"
    }
  },
  {
    "identifier": "8f130b37-8b87-5ec5-9318-4847398ed158",
    "active": true,
    "organization": "51fb5086-5a2d-54d1-9833-908daba23f82",
    "practitioner": "fc21f514-d145-513a-afb9-6f3108f14d5f",
    "code": {
      "text": "Community Health Worker"
    }
  },
  {
    "identifier": "3e50c879-fd1a-5a79-aa4f-bbca83fa363c",
    "active": true,
    "organization": "96f841eb-6478-50ef-abba-67021473d4bb",
    "practitioner": "2b2e31bf-433b-5b45-8028-4ddf7c2ecba1",
    "code": {
      "text": "Community Health Worker"
    }
  }
]
`

## I Created Plans
1. https://reveal-stage.smartregister.org/opensrp/rest/plans/a8c0485a-93b4-58f4-81b5-baf334b42ed3
2. https://reveal-stage.smartregister.org/opensrp/rest/plans/7951ce2b-a731-4362-89a5-3975113c2097

## Greg Created Case Triggered plans, but I haven't assigned them to users
1. https://reveal-stage.smartregister.org/opensrp/rest/plans/6db0e0f5-d552-42ea-ab8a-83e42eef7c45 (Assign to Organization: 79a66ddb-d563-5e99-8177-fda2ab13e384 Sinda1)
2. https://reveal-stage.smartregister.org/opensrp/rest/plans/bc78591f-df79-45a7-99e4-c1fbeda629e2 (Assign to Organization: 97809856-5c31-5a4e-abb2-efe152a0b715 Nchelenge1)
3. https://reveal-stage.smartregister.org/opensrp/rest/plans/017c2d2a-ae83-40ca-8f72-0ea35d371d81 (Assign to Organization: 96f841eb-6478-50ef-abba-67021473d4bb Chadiza1)

## Assigned Locations and Plans
1. https://reveal-stage.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans/96f841eb-6478-50ef-abba-67021473d4bb (Chadiza - I tried a level 3 jurisdiction on this one to see if it works and it doesn't)
2. https://reveal-stage.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans/51fb5086-5a2d-54d1-9833-908daba23f82 (Chiapata)
3. https://reveal-stage.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans/79a66ddb-d563-5e99-8177-fda2ab13e384 (Nchalenge)
4. https://reveal-stage.smartregister.org/opensrp/rest/organization/assignedLocationsAndPlans/97809856-5c31-5a4e-abb2-efe152a0b715 (Sinda)

## Things I have tried
1. I have double checked that all names match in the hierarchy in openmrs and reveal
2. I have double checked that all OpenMRS_Ids in reveal match OpenMRS
3. I have checked the team assignment, trying at both the lowest level (geographicLevel 4) and one above (geographicLevel 3)
4. I have verified that the plans created

**Comment by craigappl** [comment]
We fixed this today. The problem was with spaces in the names of the lowest level operational area.
